name: workflow-docker-release

on:
  push:
    tags:
      - '*'

permissions:
  packages: write
  contents: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: |
        name=ghcr.io/${{ github.repository_owner }}/arch-privoxyvpn
        docker build -t $name:latest .
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        docker push $name:latest
